<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.seabow</groupId>
    <artifactId>spark-datax</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>
    <modules>
        <module>common</module>
        <module>core</module>
    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <spark.version>3.0.2</spark.version>
        <scala.version.major>2.12</scala.version.major>
        <scala.version.minor>2.12.10</scala.version.minor>
        <hadoop.version>3.2.2</hadoop.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.scalatest</groupId>
                <artifactId>scalatest_${scala.version.major}</artifactId>
                <version>3.2.10</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>